version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      day: monday
    groups:
      nuvola:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
    groups:
      nuvola-docker:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      day: wednesday
