version: "3"

services:
  neo4j:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - logs:/logs/
      - nuvoladb:/data
      - ./backup:/backup:rw
    environment:
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_AUTH: $NEO4J_AUTH
      NEO4J_server_memory_heap_initial__size: ${NEO4J_server_memory_heap_initial__size}
      NEO4J_server_memory_heap_max__size: ${NEO4J_server_memory_heap_max__size}
      NEO4J_server_memory_pagecache_size: ${NEO4J_server_memory_pagecache_size}
      NEO4J_server_jvm_additional: "-XX:+ExitOnOutOfMemoryError"
      NEO4J_initial_dbms_default__database: "nuvoladb"
      NEO4J_dbms_cypher_forbid__shortestpath__common__nodes: "false"

volumes:
  nuvoladb:
  logs:
