name: Golang CI
on:
  push:
    branches:
      - master
      - dev
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/golangci.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/golangci.yml"

concurrency:
  group: nuvola-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        # v5.0.2
        with:
          go-version: "oldstable"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
        # v6.1.0
        with:
          version: latest
          only-new-issues: true
          args: --timeout 300s --exclude-dirs="(^|/)assets($|/)" --enable misspell --enable gofmt --enable goimports --enable whitespace

  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        # v4.2.0
      - name: Run Gosec Security Scanner
        uses: securego/gosec@6fbd381238e97e1d1f3358f0d6d65de78dcf9245
        # V.2.20.0
        with:
          args: "-exclude-dir=assets -no-fail -fmt sarif -out results.sarif ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@4b6aa0b07da05d6e43d0e5f9c8596a6532ce1c85
        # v2.15.3
        with:
          sarif_file: ./results.sarif

  go-build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        # v5.0.2
        with:
          go-version-file: "go.mod"
          cache-dependency-path: |
            go.sum
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build ./...
      - name: Test with the Go CLI
        run: go test ./...
