name: Golang CI
on:
  push:
    branches:
      - master
      - dev
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/golangci.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/golangci.yml"

concurrency:
  group: nuvola-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        # v4.1.6
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        # v5.0.1
        with:
          go-version: "oldstable"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
        # v6.0.1
        with:
          version: latest
          only-new-issues: true
          args: --timeout 300s --exclude-dirs="(^|/)assets($|/)" --enable misspell --enable gofmt --enable goimports --enable whitespace

  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        # v4.1.6
      - name: Run Gosec Security Scanner
        # master to fetch latest checks
        # kics-scan ignore-line
        uses: securego/gosec@6fbd381238e97e1d1f3358f0d6d65de78dcf9245
        # V.2.20.0
        with:
          args: "-exclude-dir=assets -no-fail -fmt sarif -out results.sarif ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@4b6aa0b07da05d6e43d0e5f9c8596a6532ce1c85
        # v2.15.3
        with:
          sarif_file: ./results.sarif

  go-build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        # v4.1.6
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        # v5.0.1
        with:
          go-version-file: "go.mod"
          cache-dependency-path: |
            go.sum
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build ./...
      - name: Test with the Go CLI
        run: go test ./...
